server:
  port: 8088
  session:
    timeout: 10
  tomcat:
    uri-encoding: UTF-8

filepath: uploadFile

logging:
  config: classpath:log4j2_dev.xml

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  redis:
    host: 192.168.0.116
    port: 6379
    pool:
      max-wait: -1
      max-idle: 8
      min_idle: 0
    timeout: 30000
  datasource:
    url: jdbc:mysql://192.168.0.116:3306/MyBlog
    username: root
    password: qf123456
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 1000
    min-idle: 5
    initial-size: 5

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: org.gift.PersistantObject.entity
